repos:
  - repo: local
    hooks:
      - id: compose-start-or-check
        name: ① start or check docker
        entry: bash scripts/precommit/01-start-or-check.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: compose-pnpm-test
        name: ② pnpm test
        entry: bash scripts/precommit/02-test.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: compose-pnpm-check
        name: ③ pnpm check
        entry: bash scripts/precommit/03-check.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: compose-pnpm-format
        name: ④ pnpm format
        entry: bash scripts/precommit/04-format.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: compose-teardown-if-started
        name: ⑤ down docker if not started previously
        entry: bash scripts/precommit/05-teardown.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
