### Test the invoke endpoint
POST http://localhost:8000/invoke
Content-Type: application/json

{
  "id": "test-123",
  "name": "Test Run",
  "blocs": {
    "bloc1": {
      "count": 50,
      "preference": {
        "slate1": "all_bets_off",
        "slate2": "random",
        "slate3": "unif",
      },
      "cohesion": {
        "slate1": 0.6,
        "slate2: 0.3,
        "slate3: 0.1,
      },
    },
    "bloc2": {
      "count": 50,
      "preference": {
        "slate1": "random",
        "slate2": "random",
        "slate3": "unif",
      },
      "cohesion": {
        "slate1": 0.7,
        "slate2: 0.2,
        "slate3: 0.1,
      },
    }
  },
  "slates": {
    "slate1": {
      "numCandidates": 3
    },
    "slate2": {
      "numCandidates": 3
    },
    "slate3": {
      "numCandidates": 4
    }
  },
  "election": {
    "mode": "blocPlurality",
    "numSeats": 3,
    "maxBallotLength":10
  },
  "ballotGenerator": "sBT",
  "trials": 50,
  "createdAt": "1700000000000"
}

### Test the root endpoint
GET http://localhost:8000/

