version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: votekit-app
    command: sh -c "pnpm i && pnpm dev --host 0.0.0.0 --port 5173"
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5173
    depends_on:
      - lambda

  lambda:
    build:
      context: ./lambda
      dockerfile: Dockerfile.dev
    container_name: votekit-lambda-dev
    volumes:
      - ./lambda:/app
    ports:
      - "8000:8000"
