name: CI (docker-compose app+lambda)

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  compose-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make temp env files
        run: |
          cp ./app/.env.example ./app/.env
          cp ./infra/.env.example ./infra/.env
          sed -i 's/TURNSTILE_SECRET_KEY=.*/TURNSTILE_SECRET_KEY=${{ secrets.TURNSTILE_SECRET_KEY_TEST }}/' ./app/.env
          sed -i 's/PUBLIC_TURNSTILE_KEY=.*/PUBLIC_TURNSTILE_KEY=${{ secrets.PUBLIC_TURNSTILE_KEY_TEST }}/' ./app/.env

      - name: Show Docker versions
        run: |
          docker --version
          docker compose version

      - name: Build and start services (app, lambda)
        run: |
          docker compose up -d --build app lambda

      - name: Wait briefly for containers to initialize
        run: sleep 10

      - name: Run tests in app (pnpm test)
        run: |
          docker compose exec -T app sh -lc "pnpm test"

      - name: Run lambda doctests (python main.py -v)
        run: |
          docker compose exec -T lambda python main.py -v 

      - name: Run io doctests (python s3_io.py)
        run: |
          docker compose exec -T lambda python s3_io.py -v

      - name: Show container logs on failure
        if: failure()
        run: |
          echo '==== app logs ===='
          docker compose logs app || true
          echo '==== lambda logs ===='
          docker compose logs lambda || true

      - name: Tear down
        if: always()
        run: |
          docker compose down -v
